// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projeto.Data;

#nullable disable

namespace projeto.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250128223822_init4")]
    partial class init4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projeto.Models.Desconto", b =>
                {
                    b.Property<int>("DescontoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DescontoId"));

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataObtencao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsLoja")
                        .HasColumnType("bit");

                    b.Property<int>("PontosNecessarios")
                        .HasColumnType("int");

                    b.Property<int?>("UtilizadorId")
                        .HasColumnType("int");

                    b.Property<double>("Valor")
                        .HasColumnType("float");

                    b.HasKey("DescontoId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("Desconto");

                    b.HasData(
                        new
                        {
                            DescontoId = 1,
                            Descricao = "10% desconto",
                            IsLoja = true,
                            PontosNecessarios = 10,
                            Valor = 10.0
                        },
                        new
                        {
                            DescontoId = 2,
                            Descricao = "20% desconto",
                            IsLoja = true,
                            PontosNecessarios = 20,
                            Valor = 20.0
                        });
                });

            modelBuilder.Entity("projeto.Models.DescontoResgatado", b =>
                {
                    b.Property<int>("DescontoResgatadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DescontoResgatadoId"));

                    b.Property<DateTime>("DataResgate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<int>("DescontoId")
                        .HasColumnType("int");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("DescontoResgatadoId");

                    b.HasIndex("DescontoId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("DescontoResgatado");
                });

            modelBuilder.Entity("projeto.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PrecoInicial")
                        .HasColumnType("float");

                    b.Property<bool>("Sustentavel")
                        .HasColumnType("bit");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.ToTable("Itens");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Categoria = 2,
                            Descricao = "Relógio luxuoso em ouro 18k.",
                            FotoUrl = "/images/relogio.jpg",
                            PrecoInicial = 500.0,
                            Sustentavel = false,
                            Titulo = "Relógio de Ouro"
                        },
                        new
                        {
                            ItemId = 2,
                            Categoria = 4,
                            Descricao = "Bicicleta clássica para colecionadores.",
                            FotoUrl = "/images/bicicleta.jpg",
                            PrecoInicial = 200.0,
                            Sustentavel = true,
                            Titulo = "Bicicleta Vintage"
                        });
                });

            modelBuilder.Entity("projeto.Models.Leilao", b =>
                {
                    b.Property<int>("LeilaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeilaoId"));

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime2");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<double>("ValorIncrementoMinimo")
                        .HasColumnType("float");

                    b.Property<string>("Vencedor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LeilaoId");

                    b.HasIndex("ItemId");

                    b.ToTable("Leiloes");

                    b.HasData(
                        new
                        {
                            LeilaoId = 1,
                            DataFim = new DateTime(2025, 1, 28, 23, 10, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 1, 28, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemId = 1,
                            ValorIncrementoMinimo = 5.0
                        },
                        new
                        {
                            LeilaoId = 2,
                            DataFim = new DateTime(2025, 1, 28, 22, 45, 0, 0, DateTimeKind.Unspecified),
                            DataInicio = new DateTime(2025, 1, 28, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            ItemId = 2,
                            ValorIncrementoMinimo = 10.0
                        });
                });

            modelBuilder.Entity("projeto.Models.Licitacao", b =>
                {
                    b.Property<int>("LicitacaoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LicitacaoId"));

                    b.Property<DateTime>("DataLicitacao")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LeilaoId")
                        .HasColumnType("int");

                    b.Property<double>("ValorLicitacao")
                        .HasColumnType("float");

                    b.HasKey("LicitacaoId");

                    b.HasIndex("LeilaoId");

                    b.ToTable("Licitacoes");
                });

            modelBuilder.Entity("projeto.Models.LogUtilizador", b =>
                {
                    b.Property<int>("LogUtilizadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogUtilizadorId"));

                    b.Property<bool>("IsLoginSuccess")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LogDataLogin")
                        .HasColumnType("datetime2");

                    b.Property<string>("LogMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogUtilizadorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("LogUtilizadorId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("LogUtilizadores");
                });

            modelBuilder.Entity("projeto.Models.LoginModel", b =>
                {
                    b.Property<int>("LoginModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoginModelId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoginModelId");

                    b.ToTable("LoginModel");
                });

            modelBuilder.Entity("projeto.Models.Utilizador", b =>
                {
                    b.Property<int>("UtilizadorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UtilizadorId"));

                    b.Property<string>("CodigoPostal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoConta")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Morada")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pais")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Pontos")
                        .HasColumnType("int");

                    b.Property<string>("Telemovel")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("UtilizadorId");

                    b.ToTable("Utilizador");
                });

            modelBuilder.Entity("projeto.Models.VerificationModel", b =>
                {
                    b.Property<int>("VerificationModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerificationModelId"));

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("VerificationCode")
                        .HasColumnType("int");

                    b.HasKey("VerificationModelId");

                    b.ToTable("VerificationModel");
                });

            modelBuilder.Entity("projeto.Models.Desconto", b =>
                {
                    b.HasOne("projeto.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("projeto.Models.DescontoResgatado", b =>
                {
                    b.HasOne("projeto.Models.Desconto", "Desconto")
                        .WithMany()
                        .HasForeignKey("DescontoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projeto.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desconto");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("projeto.Models.Leilao", b =>
                {
                    b.HasOne("projeto.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("projeto.Models.Licitacao", b =>
                {
                    b.HasOne("projeto.Models.Leilao", null)
                        .WithMany("Licitacoes")
                        .HasForeignKey("LeilaoId");
                });

            modelBuilder.Entity("projeto.Models.LogUtilizador", b =>
                {
                    b.HasOne("projeto.Models.Utilizador", "Utilizador")
                        .WithMany()
                        .HasForeignKey("UtilizadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("projeto.Models.Leilao", b =>
                {
                    b.Navigation("Licitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
